<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_app_description'] = 'Приложение "Базовый отчет" предоставляет набор стандартных инструментов отчета для операционной системы.';
$lang['reports_app_name'] = 'Базовый отчет';
$lang['reports_date_range'] = 'Диапазон дат';
$lang['reports_device_type_summary'] = 'Сводка типа устройств';
$lang['reports_device_types'] = 'Тип устройств';
$lang['reports_entries'] = 'Записи';
$lang['reports_full_report'] = 'Полный отчет';
$lang['reports_ip_summary'] = 'Сводка IP';
$lang['reports_last_30_days'] = 'Последние 30 дней';
$lang['reports_last_7_days'] = 'Последние 7 дней';
$lang['reports_live'] = 'Live';
$lang['reports_range_invalid'] = 'Диапазон является недействительным.';
$lang['reports_report_data'] = 'Данные отчета';
$lang['reports_report_settings'] = 'Настройки отчета';
$lang['reports_reports'] = 'Отчет';
$lang['reports_today'] = 'Сегодня';
$lang['reports_top_device_types'] = 'Главные типы устройств';
$lang['reports_top_external_ips'] = 'Top External IPs';
$lang['reports_top_ips'] = 'Top IPs';
$lang['reports_top_users'] = 'Top Users';
$lang['reports_user_summary'] = 'Сводка пользователей';
$lang['reports_yesterday'] = 'Вчера';
