#!/bin/sh

# Get the internal database going
#--------------------------------

logger -p local6.notice -t installer "app-reports-core - initializing system database"
/usr/clearos/apps/reports/deploy/initialize-database >/dev/null 2>&1

