<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_app_description'] = 'The Base Reports app provides a set of standard report tools for the operating system.';
$lang['reports_app_name'] = 'Base Reports';
$lang['reports_date_range'] = 'Date Range';
$lang['reports_device_type_summary'] = 'Device Type Summary';
$lang['reports_device_types'] = 'Device Types';
$lang['reports_entries'] = 'Entries';
$lang['reports_full_report'] = 'Full Report';
$lang['reports_ip_summary'] = 'IP Summary';
$lang['reports_last_30_days'] = 'Last 30 Days';
$lang['reports_last_7_days'] = 'Last 7 Days';
$lang['reports_range_invalid'] = 'Range is invalid.';
$lang['reports_report_data'] = 'Report Data';
$lang['reports_report_settings'] = 'Report Settings';
$lang['reports_reports'] = 'Reports';
$lang['reports_today'] = 'Today';
$lang['reports_top_device_types'] = 'Top Device Types';
$lang['reports_top_external_ips'] = 'Top External IPs';
$lang['reports_top_ips'] = 'Top IPs';
$lang['reports_top_users'] = 'Top Users';
$lang['reports_user_summary'] = 'User Summary';
$lang['reports_yesterday'] = 'Yesterday';
