<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_app_description'] = 'De grundläggande rapporterna ger en uppsättning av standardrapporter från operativsystemet.';
$lang['reports_app_name'] = 'Grundläggande rapporter';
$lang['reports_date_range'] = 'Datumintervall';
$lang['reports_device_type_summary'] = 'Device Type Summary';
$lang['reports_device_types'] = 'Device Types';
$lang['reports_entries'] = 'Data';
$lang['reports_full_report'] = 'Fullständig rapport';
$lang['reports_ip_summary'] = 'IP Summary';
$lang['reports_last_30_days'] = 'De senaste 30 dagarna';
$lang['reports_last_7_days'] = 'De senaste 7 dagarna';
$lang['reports_range_invalid'] = 'Intervallet är ogiltigt.';
$lang['reports_report_data'] = 'Rapportdata';
$lang['reports_report_settings'] = 'Rapportinställningar';
$lang['reports_reports'] = 'Rapporter';
$lang['reports_today'] = 'Idag';
$lang['reports_top_device_types'] = 'Top Device Types';
$lang['reports_top_external_ips'] = 'Top External IPs';
$lang['reports_top_ips'] = 'Top IPs';
$lang['reports_top_users'] = 'Top Users';
$lang['reports_user_summary'] = 'User Summary';
$lang['reports_yesterday'] = 'Igår';
