<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_app_description'] = 'De grundläggande rapporterna ger en uppsättning av standardrapporter från operativsystemet.';
$lang['reports_app_name'] = 'Grundläggande rapporter';
$lang['reports_date_range'] = 'Datumintervall';
$lang['reports_entries'] = 'Data';
$lang['reports_full_report'] = 'Fullständig rapport';
$lang['reports_last_30_days'] = 'De senaste 30 dagarna';
$lang['reports_last_7_days'] = 'De senaste 7 dagarna';
$lang['reports_range_invalid'] = 'Intervallet är ogiltigt.';
$lang['reports_report_data'] = 'Rapportdata';
$lang['reports_report_settings'] = 'Rapportinställningar';
$lang['reports_reports'] = 'Rapporter';
$lang['reports_today'] = 'Idag';
$lang['reports_yesterday'] = 'Igår';
