<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_app_description'] = 'Aplikacja podstawowych raportów dostarcza zestaw standardowych narzędzi do raportowania stanu systemu operacyjnego.';
$lang['reports_app_name'] = 'Podstawowe raporty';
$lang['reports_date_range'] = 'Zakres dat';
$lang['reports_entries'] = 'Wpisy';
$lang['reports_full_report'] = 'Pełny raport';
$lang['reports_last_30_days'] = 'Ostatnie 30 dni';
$lang['reports_last_7_days'] = 'Ostatnie 7 dni';
$lang['reports_range_invalid'] = 'Podany zakres jest nieprawidłowy.';
$lang['reports_report_data'] = 'Dane raportu';
$lang['reports_report_settings'] = 'Ustawienia raportu';
$lang['reports_reports'] = 'Raporty';
$lang['reports_today'] = 'Dziś';
$lang['reports_yesterday'] = 'Wczoraj';
