<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_app_description'] = 'Aplikacja podstawowych raportów dostarcza zestaw standardowych narzędzi do raportowania stanu systemu operacyjnego.';
$lang['reports_app_name'] = 'Podstawowe raporty';
$lang['reports_date_range'] = 'Zakres dat';
$lang['reports_device_type_summary'] = 'Device Type Summary';
$lang['reports_device_types'] = 'Device Types';
$lang['reports_entries'] = 'Wpisy';
$lang['reports_full_report'] = 'Pełny raport';
$lang['reports_ip_summary'] = 'IP Summary';
$lang['reports_last_30_days'] = 'Ostatnie 30 dni';
$lang['reports_last_7_days'] = 'Ostatnie 7 dni';
$lang['reports_range_invalid'] = 'Podany zakres jest nieprawidłowy.';
$lang['reports_report_data'] = 'Dane raportu';
$lang['reports_report_settings'] = 'Ustawienia raportu';
$lang['reports_reports'] = 'Raporty';
$lang['reports_today'] = 'Dziś';
$lang['reports_top_device_types'] = 'Top Device Types';
$lang['reports_top_external_ips'] = 'Top External IPs';
$lang['reports_top_ips'] = 'Top IPs';
$lang['reports_top_users'] = 'Top Users';
$lang['reports_user_summary'] = 'User Summary';
$lang['reports_yesterday'] = 'Wczoraj';
